### ISSUE TITLE
react-addons deprecated

### ISSUE THREAD

**Issue by benjaminEwhite** [Thinkful-Ed/react-trello-testing#1]
since this repo is pinned to React 15.4, no issue here, but we should upgrade to 15.5, which deprecates react-addons

test-utils now ships with react-dom

so `import ReactTestUtils from 'react-dom/test-utils';`

**Comment by benjaminEwhite** [comment]
also: https://github.com/airbnb/enzyme#installation

now need to install `react-test-renderer` along with `react-dom` (that second one we already have) alongside enzyme.

**Comment by oampo** [comment]
Fixed in 41e2ce45a5dc1f13e77cafc219f109d368851dd2
